tasks:
  # task name
  - name: "Check last telegram post date"

  # string for scheduling in crontab-like syntax (see https://crontab.guru).
  schedule: "29 13-20 * * 1-5"

  # scenario type
  scenario: "xpath"

  # path to file wuth messages list to be send
  messages: "./messages.yml"

  # page that will be parsed
  url: "https://t.me/s/codex_team"

  # xpath expression for wat—Åhing element
  xpath: "/html/body/main/div/section/div[20]/div[1]/div[2]/div[3]/div/span[3]/a/time"

  hooks:

    # on_changed action
    changed:
      notifier: "Telegram"

    # on_no-changed action
    no-changes:
      notifier: "Work Email"
      time: 40000

notifiers:
  - name: "Telegram"
  type: "telegram"
  webhook: "https://notify.bot.codex.so/u/R4ND0M"
    - name: "Work Email"
  type: "email"
  address: "work@me.ru"

# database settings section (optional)

database:
  # hostname or IP address of a MongoDB instance to connect to
  # see <https://api.mongodb.com/python/current/api/pymongo/mongo_client.html>
  host: localhost

  # port of a MongoDB instance
  port: 27017

  # name of the database
  name: manager
