version: "3"
services:
  managerai:
    build: .
    volumes:
      - .:/home/manager-ai/
      - ./config.docker.yml:/home/manager-ai/config.yml
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.2
    ports:
      - 27017:27017

volumes:
  mongodata: