version: "3"
services:
  managerai:
    build: .
    volumes:
      - .:/home/manager-ai/
      - ./env-config/config-docker.yml:/home/manager-ai/manager-ai/config.yml
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.2
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata: